# MAIN base
baseURL = "https://ril-ci.org"
languageCode = "fr-fr"
title = "Coming Soon | Organisation coming soon template"
theme = "coming-soon"

# Navigation Bar
[[menu.main]]
    name = "Nos projets"
    url = "#projets"
    weight = 1

# Footer Social
[params.social]
facebook = "https://www.facebook.com/Reseauivoiriendesleaders"
twitter = "https://instagram.com/ril_225"
github = "https://github.com/Reseau-Ivoirien-des-Leaders"

[params]

# Header
logo = "images/logo.png"
fabFormURL = "https://fabform.io/f/eqkiNxm"
googleAnalytics = "UA-175025671-2"

# Footer
footerTitle = "Recevez nos informations par email"
copyright1 = "Développé par "
copyright2 = "©  <a href=\"https://www.meetdemocracy.com/\" target=\"_blank\">Meet Democracy </a>"

#contact
email = "info@ril-ci.org"
